const nodemailer = require('nodemailer');
require('dotenv').config();

const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',  // ✅ explicit host instead of service:'gmail'
  port: 465,
  secure: true,
  family: 4,               // ✅ force IPv4 (fixes Render's ENETUNREACH error)
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
  tls: {
    rejectUnauthorized: false
  }
});

const sendSummaryEmail = async (recipientEmail, summary) => {
  const mailOptions = {
    from: `"Sales Insight Automator 🤖" <${process.env.GMAIL_USER}>`,
    to: recipientEmail,
    subject: '📊 Your AI Sales Summary Report',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 700px; margin: auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
        <h2 style="color: #1a73e8;">📊 Sales Insight Report</h2>
        <p style="color: #555;">Hello,</p>
        <p style="color: #555;">Your AI-generated sales summary is ready. Here are the key insights:</p>
        <hr style="border: none; border-top: 1px solid #e0e0e0;" />
        <div style="background: #f9f9f9; padding: 16px; border-radius: 6px; white-space: pre-wrap; color: #333; line-height: 1.7;">
          ${summary.replace(/\n/g, '<br/>')}
        </div>
        <hr style="border: none; border-top: 1px solid #e0e0e0;" />
        <p style="color: #999; font-size: 12px;">Generated by Sales Insight Automator · Powered by Groq AI</p>
      </div>
    `,
  };

  await transporter.sendMail(mailOptions);
};

module.exports = { sendSummaryEmail };